### ISSUE TITLE
Update the description of the repository

### ISSUE THREAD

**Issue by deshankoswatte** [yashodgayashan/environment_platform#22]
Currently as show in the **screenshot below** we don't have a description of what's inside the repository and the purpose of the containment. I suggest that we _add a nice description_ to it so that the external parties are aware of the repository. I think only the repository owner can add it.

![Screenshot from 2020-05-15 22-00-56](https://user-images.githubusercontent.com/33062368/82073917-9343bd00-96f7-11ea-87f8-3faef4c9ebb4.png)

**Comment by deshankoswatte** [comment]
@yashodgayashan Please add the suggestions here so that we can decide on a proper description.

**Comment by yashodgayashan** [comment]
> Environment platform is a system to manage any activity which will involve with the environment and which is mainly used in Environment Ministry Sri Lanka. This system is capable of track any activity such as tree cutting, reforestation etc and manage those. 

Above is my suggestion what do you think about it? @deshankoswatte @sanjulamadurapperuma @vikumkbv @achala87

**Comment by deshankoswatte** [comment]
@sanjulamadurapperuma, @yashodgayashan, @vikumkbv can we proceed with this?

**Comment by vikumkbv** [comment]
Yes we can

**Comment by deshankoswatte** [comment]
Yeah we need a good description @yashodgayashan, @sanjulamadurapperuma, @vikumkbv and @achala87.

**Comment by yashodgayashan** [comment]
**Environment platform is a system to manage any activity which will involve with the environment and which is mainly used in Environment Ministry Sri Lanka. This system is capable of track any activity such as tree cutting, reforestation etc and manage those.** 

@deshankoswatte is this good enough or do we need to describe more?

**Comment by sanjulamadurapperuma** [comment]
@yashodgayashan No this could be improved. Give me some time, I'll update it

**Comment by deshankoswatte** [comment]
@sanjulamadurapperuma please suggest a good one so that we can finalize that. And sorry guys I'm out of thoughts for the description :(

**Comment by deshankoswatte** [comment]
@sanjulamadurapperuma, @yashodgayashan any updates on this?

**Comment by yashodgayashan** [comment]
@deshankoswatte I will update this on tomorrow.

**Comment by sanjulamadurapperuma** [comment]
**A comprehensive online request management platform for the Ministry of Environment and Wildlife Resources, Sri Lanka**

What do you think about this? A description on a Github repo is usually short and to the point, so this should work. @yashodgayashan @deshankoswatte @vikumkbv

**Comment by deshankoswatte** [comment]
> **A comprehensive online request management platform for the Ministry of Environment and Wildlife Resources, Sri Lanka**
> 
> What do you think about this? A description on a Github repo is usually short and to the point, so this should work. @yashodgayashan @deshankoswatte @vikumkbv

I like this. Others @vikumkbv, @yashodgayashan thoughts of you guys?

**Comment by yashodgayashan** [comment]
@sanjulamadurapperuma That is simple and great. @deshankoswatte I like this.

**Comment by deshankoswatte** [comment]
@vikumkbv after your approval we can set the description.

**Comment by deshankoswatte** [comment]
@yashodgayashan will proceed with this. Please change the description to what @sanjulamadurapperuma has suggested.

**Comment by yashodgayashan** [comment]
@deshankoswatte ack.
